version: '3.7'

networks:
  bridge:
    external:
      name: ${NETWORKS}

services:
  pick:
    image: nginx:alpine
    container_name: 0verPick
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/dist/:/usr/share/nginx/html/review/
    networks:
      - bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pick.entrypoints=websecure"
      - "traefik.http.routers.pick.tls.certresolver=lets-encr"
      - "traefik.http.routers.pick.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/review`)"
      - "traefik.http.routers.pick.tls.options=default"
      - "traefik.http.routers.pick.middlewares=secure-headers@file,traefik-compress@file"